### PR TITLE
ARQ-2016 Allow custom extensions for the OSGi container

### PR DESCRIPTION
**Pull request by cgoncas**
We have adapt the Arquillian OSGi Extension so it can use custom extensions, now we are using it sucessfully in the Arquillian Liferay Extension.

The idea that we have implemented is:

1. The Arquillian OSGi Bundle is automatically generated (with all the extensions that are declared in the classpath). (This is done only once)
2. For every test:
  2.1. The Arquillian OSGi Bundle is installed.
  2.2. The test deployment is installed without any enhacement.
  2.3. A fragment for the Arquillian OSGI Bundle that contains only the test class is generated and installed.
  2.4 The tests are executed
  2.5 All the previously installed bundle are uninstalled.

We think that this maybe can be usefull for someone. Maybe it would be interesting try to merge it with the current Arquillian OSGi Container.

What do you think? If you need more information, please, let us know.

Thanks!

@csierra

### CODE REVIEW

**Comment by lordofthejars** [comment]
Thank you very much for contribution, I suppose you need a new version on maven central right?

**Comment by cgoncas** [comment]
Hey @lordofthejars , you are welcome. @tdiesler released a new maven version early this week.

**Comment by vkasala** [comment]
Hello @cgoncas, @lordofthejars,

ARQ-2016 break our testcases, where we used inheritance in test classes and custom JUnit runners. With newest version, we do not know how to add all the neccessary test classes into test-fragment.jar and also all the other dependent data files. Can you help me with that? What is the proposed solution for that? I got following exception:

`Caused by: java.lang.ClassNotFoundException: org.jboss.test.arquillian.container.BaseTest from [Module "jbosgi.arquillian-osgi-bundle:1.0.0.bid44rev0" from FrameworkModuleLoaderImpl]
        at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:197)
`
Attached simple testcase:

`@RunWith(Arquillian.class)
public class TestInheritenceTestCase extends BaseTest {
	@Deployment
	public static JavaArchive createdeployment() {
		final JavaArchive archive = ShrinkWrap.create(JavaArchive.class, "test.jar");
		archive.setManifest(new Asset() {
			public InputStream openStream() {
				OSGiManifestBuilder builder = OSGiManifestBuilder.newInstance();
				builder.addBundleSymbolicName(archive.getName());
				builder.addBundleManifestVersion(2);
				builder.addImportPackages(Bundle.class);
				return builder.openStream();
			}
		});
                archive.addClassess(BaseTest.class, OtherClasses....);
		return archive;
	}
	@Test
	public void testInheritance() throws Exception {
		assertEquals("System Bundle ID", "HELLO_WORLD", BaseTest.HELLO_I_SHOULD_BE_IN_THE_TEST_PACKAGE);
	}
}`

**Comment by cgoncas** [comment]
Hey @vkasala ,

I've just created a pull with your example and everything just work fine:

https://github.com/arquillian/arquillian-container-osgi/pull/54

Can you create a pull that breaks the tests?

Thanks!

**Pull request merged**
