### PR TITLE
Fix deployment strategy

### PR DESCRIPTION
**Pull request by bouskaJ**
This Pull request fixes shortcomings which are described in https://github.com/arquillian/arquillian-container-osgi/pull/54.

This PR is based on the "old" deployment approach (before https://github.com/arquillian/arquillian-container-osgi/commit/a663171012cc6409744a394f0f1ac5b689151ce4) but it fixes problems with loading Arquillian extensions.
Moreover I upgraded to latest Arquillian BOM version and Java 1.8.

### CODE REVIEW

**Comment by bouskaJ** [comment]
@lordofthejars Can you review and merge this MR?

**Comment by bouskaJ** [comment]
@tdiesler Can you review and merge this MR?

**Comment by tdiesler** [comment]
This needs to be squashed and associated with one single issue that describes why the changes are needed.

**Comment by bouskaJ** [comment]
Hi @tdiesler I just open new PR (from new branch) which squashed commits and better description https://github.com/arquillian/arquillian-container-osgi/pull/56. I am closing this in favor of the new MR. Thank for the review.

**Comment by tdiesler** [comment]
Again, could you please reference a jira issue that describes what the problem is and how it is being fixed.

**Pull request closed without merging**
