### PR TITLE
ARQ-2016 Add Inherence Test

### PR DESCRIPTION
**Pull request by cgoncas**
#### Short description of what this resolves:
New Inherence test

#### Changes proposed in this pull request:

- Add new Inherence test, to check that these type of tests works just fine.

### CODE REVIEW

**Comment by vkasala** [comment]
Hi @cgoncas,

you forgot to add annotation @RunWith(Arquillian.class). We have a complex deployment scenario, where we have inheritance in test case classes and also we need to add utility classes into archive, because parent classes need them. Also sometimes, we need to add data file with some data or persitance.xml. Your proposed solution creates two bundles: 

- **arquillian-osgi-bundle** - contains all arquillian, junit deps, ... and 
- **test-case-bundle** - contains fragment with only one class - the test class. Also it contains all the other classes/resources which we add through archive.addClasses. However, the fragment test bundle does not see them.

Viliam

**Comment by cgoncas** [comment]
All Arquillian Extensions are included inside the fragment.

The OSGi extension now keeps the usual Arquillian Lifecycle.

**Comment by vkasala** [comment]
What about the forgotten @RunWith(Arquillian.class) annotation? It does not work with the annotation. Did you try it?

**Comment by vkasala** [comment]
Your Inheritance test does not work as expeceted, because you forgot annotation @RunWith(Arquillian.class). Can you help me with that?

Thanks.

**Comment by cgoncas** [comment]
I've added a commit with the runner now, you can check that everything works as expected

**Comment by vkasala** [comment]
Hi, thanks @cgoncas for your response. I checked your Commit, however your subclass BaseClass is in different package. 

What if subclasses are in the same package? Then it does not work, because test-fragment has field Private-package. So I can export, however the test-fragment will not look in another bundle.

What if there are other utility classes which are not subclasses? What if I need to add some resource into test-fragment bundle? How should I deal with that? It worked for us with the older version.

Thanks and I reall appreciate your help.

V.

**Comment by cgoncas** [comment]
Hey @vkasala 

The split package issue that you are talking about, is a OSGi prerrequisite, yo can't share packages names between bundles, you can found more documentation in: https://nirmalsasidharan.wordpress.com/2010/09/02/split-packages-an-osgi-nightmare/.

Of course you can use the old version, if you don't want to deal with the OSGi complexities of the bundles, but if you use the old version, it is not possible to use custom Arquillian extension that keep the Arquillian Lifecycle.

You can add all the utilities classes that you want to the deploy bundle, and use it as a standard bundle.

I don't see the problem here, sorry.

Now the extensions works as follor:

1. Arquillian create a bundle with all the Arquillian Extensions declared as RemoteExtensions.
2. Arquillian create a fragment **only** with the test class.

You can create as many bundles as you need to your project, if they export the needed packages and can be consumed by the fragment.

Thanks!

**Comment by bouskaJ** [comment]
Hi @cgoncas 
I am also struggling with your changes. I have made a reproducer with my deployment scenario - please see https://github.com/bouskaJ/arquillian-container-osgi/commit/0be58b2c2b471a25dcb5076d196afa838b6f8ed5. There is several issues which I was not able to solve.

1) As you can see ParentTest imports org.junit and org.junit.runner packages These packages are contained in arquillian-osgi-bundle but are not exported (reproduced in https://github.com/bouskaJ/arquillian-container-osgi/commit/be460e249ab911e331cdb88c8eb13010a1484f2d)

2) Wrong order of deployment - test.jar is deployed before arquillian-osgi-bundle so even if you fix export packages (see #1) you still can't deploy test.jar (missing requirement osgi.wiring.package)

3) Even though you fix previous you still can't run test successfully - fragment.jar contains only ComplexDeploymentTest - parent class needs to be imported but we can't import the same package as we use for testClass.

This issues led me for thinking about concept of separating deployment (your app) from test-classes do you really think that that is needed? It brings a lot of issues from my point of view.

I tryed to bypass all this problems with import/export packages etc. and make my deployment also framgment of arquillian-osgi-bundle but it failed on https://github.com/arquillian/arquillian-container-osgi/blob/master/bundle/src/main/java/org/jboss/arquillian/osgi/ArquillianBundleActivator.java#L163

Could you suggest me some solution?
Thanks.

**Comment by cgoncas** [comment]
Hey @bouskaJ !!

As we said before, it is totally fine to use the old extension, if it makes the work for you :).

Otherwise, I think, as you want to extend the JUnit behaviour, would be quite easy to create your custom Arquillian Extension, and add here all the JUnit code you need for your tests.

Thanks!!!

**Comment by tdiesler** [comment]
Done

**Pull request closed without merging**
